language: python
sudo: false
cache:
  pip: true
  directories:
    - $HOME/buildout-cache
python:
  - 2.7
matrix:
  include:
    - python: "3.7"
      env: PLONE_VERSION=5.2.x
before_install:
  - mkdir -p $HOME/buildout-cache/{eggs,downloads}
  - mkdir $HOME/.buildout
  - echo "[buildout]" > $HOME/.buildout/default.cfg
  - echo "download-cache = $HOME/buildout-cache/downloads" >> $HOME/.buildout/default.cfg
  - echo "eggs-directory = $HOME/buildout-cache/eggs" >> $HOME/.buildout/default.cfg
install:
  - sed -ie "s#plone-x.x.x.cfg#plone-$PLONE_VERSION.cfg#" travis.cfg
  - pip install -r requirements.txt
  - buildout -c travis.cfg
script:
  - bin/code-analysis
  - bin/test
after_success:
  - bin/createcoverage
  - pip install coverage==3.7 coveralls
  - coveralls

notifications:
  email:
    - info@kitconcept.com
